swagger_ui:
  path: /documentation
  controller: api_platform.swagger.action.ui

api_login_check:
  path: /api/authentication_token

gesdinet_jwt_refresh_token:
  path:       /api/token/refresh
  controller: gesdinet.jwtrefreshtoken::refresh
