api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json:
            mime_types: ['application/json', 'application/merge-patch+json']
        jsonapi:  ['application/vnd.api+json']
    formats:
        json:
            mime_types: ['application/json', 'application/merge-patch+json']
        jsonld:
            mime_types: ['application/ld+json']
    enable_swagger_ui: true
    enable_docs: true
    eager_loading:
        force_eager: false
    collection:
        pagination:
            client_enabled: true
            client_items_per_page: true
            enabled_parameter_name: pagination
            items_per_page: 10

    exception_to_status:
        # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
        Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
        ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
        ApiPlatform\Core\Exception\FilterValidationException: 400
        Doctrine\ORM\OptimisticLockException: 409

        # Custom mapping
        App\Exception\PaymentException: 406
        App\Exception\PaymentPartialException: 404

    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header
