framework:
    messenger:
        default_bus: command.bus
        buses:
            command.bus:
                default_middleware: allow_no_handlers
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        serializer:
            default_serializer: messenger.transport.symfony_serializer
            symfony_serializer:
                format: json
                context: { }

        transports:
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                serializer: messenger.transport.symfony_serializer
            verified_async:
                dsn: '%env(RABBIT_MESSENGER_TRANSPORT_DSN)%'
                options:
                    exchange:
                        name: verified_async_352_01
                    queues:
                        verified_async_352_01: ~
                serializer: messenger.transport.symfony_serializer
            failed: '%env(MESSENGER_TRANSPORT_DSN)%'
            sync: 'sync://'

        failure_transport: failed

        routing:
            'App\Messenger\MessagePublish\EcsdMessage': async
            'App\Messenger\MessagePublish\VerifiedMessage': verified_async

